version: 0.2

phases: 
    install:
        runtime-versions:
            java: 17
        commands:
            - echo "installing something"
            - sudo yum install maven -y
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
            - echo $JAVA_HOME
            - mvn package
    post_build:
        commands:
            - echo "we are in the post build phase"
            - ls
artifacts:
    files:
        - targets/*.jar
        -discard-paths: yes
            
