version: 0.2
phases:
  install:
    runtime-versions:
      java: 17
    commands:
      - echo "installing something"
      - sudo yum install maven -y
      - java --version
  pre_build:
    commands:
      - echo "we are in the pre build phase"
      - export PATH=$JAVA_HOME/jre/bin:$PATH
      - echo $PATH
  build:
    commands:
      - echo "we are in the build block"
      - echo "we will run some tests"
      - java --version
      - ls /usr/lib/jvm/java-17/
      - ls /usr/lib/jvm/java-17/jre/
      - export JAVA_HOME=/usr/lib/jvm/java-17/
      - sudo ln -s $JAVA_HOME/jre $JAVA_HOME/jre/bin/java
      - mvn test
      - ls
  post_build:
    commands:
      - echo "we are in the post build phase"
artifacts:
  files:
    - targets/*.jar
  discard-paths: 'yes'
