version: 0.2
env:
  variables:
    JAVA_HOME: "usr/lib/jvm/java-17-amazon-correto/jdk"
phases:
  install:
    runtime-versions:
      java: 17
    commands:
      - echo "installing something"
      - sudo yum install maven -y
      - java --version
  pre_build:
    commands:
      - echo "we are in the pre build phase"
      - export PATH=$JAVA_HOME/jre/bin:$PATH
      - echo $JAVA_HOME
      - echo $PATH
  build:
    commands:
      - echo "we are in the build block"
      - echo "we will run some tests"
      - sudo ln -s /usr/lib/jvm/java-17-amazon-correto/jre /usr/lib/jvm/java-17-amazon-correto/jre/bin/java
      - mvn test
      - ls
  post_build:
    commands:
      - echo "we are in the post build phase"
artifacts:
  files:
    - targets/*.jar
  discard-paths: 'yes'
